version: "3.4"

x-common-env-vars: &common-env-vars
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@postgres:5432
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@postgres:5432
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__FERNET_KEY: "d6Vefz3G9U_ynXB3cr7y_Ak35tAHkEGAVxuz_B-jzWw="
  AIRFLOW__WEBSERVER__SECRET_KEY: "astro_8f9b21"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  ASTRONOMER_ENVIRONMENT: local

networks:
  airflow:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  airflow_logs:
    driver: local

services:
  postgres:
    image: docker.io/postgres:12.6
    restart: unless-stopped
    networks:
      - airflow
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  scheduler:
    image: astro_8f9b21/airflow:latest
    command: >
      bash -c "(airflow db upgrade || airflow upgradedb) && airflow scheduler"
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-scheduler"
    depends_on:
      - postgres
    environment: *common-env-vars
    volumes:
      - "C:/Users/sky031891/astro/dags:/usr/local/airflow/dags:z"
      - "C:/Users/sky031891/astro/plugins:/usr/local/airflow/plugins:z"
      - "C:/Users/sky031891/astro/include:/usr/local/airflow/include:z"
      - "C:/Users/sky031891/astro/tests:/usr/local/airflow/tests:z"
      - "C:/Users/sky031891/astro/dir:/usr/local/airflow/dir:z"
      - "C:/Users/sky031891/astro/dir/agg:/usr/local/airflow/dir/agg:z"
      - "C:/Users/sky031891/astro/dir/download:/usr/local/airflow/dir/download:z"
      - "C:/Users/sky031891/astro/dir/stage:/usr/local/airflow/dir/stage:z"

      - "C:/Users/sky031891/astro/airflow_settings.yaml:/usr/local/airflow/airflow_settings.yaml:z"

      - airflow_logs:/usr/local/airflow/logs

  webserver:
    image: astro_8f9b21/airflow:latest
    command: >
      bash -c 'if [[ -z "$$AIRFLOW__API__AUTH_BACKEND" ]] && [[ $$(pip show -f apache-airflow | grep basic_auth.py) ]];
        then export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth ;
        else export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default ; fi &&
        { airflow users create "$$@" || airflow create_user "$$@" ; } &&
        { airflow sync-perm || airflow sync_perm ;} &&
        airflow webserver' -- -r Admin -u admin -e admin@example.com -f admin -l user -p admin
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-webserver"
    depends_on:
      - scheduler
      - postgres
    environment: *common-env-vars
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - "C:/Users/sky031891/astro/dags:/usr/local/airflow/dags:z"
      - "C:/Users/sky031891/astro/plugins:/usr/local/airflow/plugins:z"
      - "C:/Users/sky031891/astro/include:/usr/local/airflow/include:z"
      - "C:/Users/sky031891/astro/tests:/usr/local/airflow/tests:z"
      - "C:/Users/sky031891/astro/dir:/usr/local/airflow/dir:z"
      - "C:/Users/sky031891/astro/dir/agg:/usr/local/airflow/dir/agg:z"
      - "C:/Users/sky031891/astro/dir/download:/usr/local/airflow/dir/download:z"
      - "C:/Users/sky031891/astro/dir/stage:/usr/local/airflow/dir/stage:z"

      - airflow_logs:/usr/local/airflow/logs

    healthcheck:
      test: curl --fail http://webserver:8080/health || exit 1
      interval: 2s
      retries: 15
      start_period: 5s
      timeout: 60s

  triggerer:
    image: astro_8f9b21/airflow:latest
    command: >
      bash -c "(airflow db upgrade || airflow upgradedb) && airflow triggerer"
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-triggerer"
    depends_on:
      - postgres
    environment: *common-env-vars
    volumes:
      - "C:/Users/sky031891/astro/dags:/usr/local/airflow/dags:z"
      - "C:/Users/sky031891/astro/plugins:/usr/local/airflow/plugins:z"
      - "C:/Users/sky031891/astro/include:/usr/local/airflow/include:z"
      - "C:/Users/sky031891/astro/tests:/usr/local/airflow/tests:z"
      - "C:/Users/sky031891/astro/dir:/usr/local/airflow/dir:z"
      - "C:/Users/sky031891/astro/dir/agg:/usr/local/airflow/dir/agg:z"
      - "C:/Users/sky031891/astro/dir/download:/usr/local/airflow/dir/download:z"
      - "C:/Users/sky031891/astro/dir/stage:/usr/local/airflow/dir/stage:z"

      - airflow_logs:/usr/local/airflow/logs
